project:
  type: book
  render:
    - "*.qmd"
    - "reports/*.qmd"
  output-dir: ../docs

book:
  title: "Quantitative Methods Committee"
  author: "Rick Gilmore"
  date: last-modified
  chapters:
    - href: index.qmd
    - href: work.qmd
    - href: courses.qmd
    - href: 2023-fall-grad-survey.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true

editor: source
    