# Agenda

This page summarizes some of the projects the committee might choose to work on.

## Open science/open scholarship

- Consolidating existing open science/open scholarship expertise in the department
- Promoting these topics more widely in our research, teaching and training, including at the undergraduate level

## Forging partnerships

- Should the committee seek to identify possible partners across the university and work to strengthen ties with them?

## Information gathering

- Do we need more or better information about quantitative methods use and needs in the department?

## Curriculum assessment

- Work with faculty who teach *undergraduate* methods and statistics courses to support their work
- Do you want or need to support new graduate coursework in the following topics:
  - Data management and sharing
  - Data visualization
  - Software development including version control
  - Research notebooks, e.g., [Jupyter notebooks](https://jupyter.org) and [Quarto](https://quarto.org)
  
